// <auto-generated />
namespace EveIndustry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedorderstable1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedorderstable1));
        
        string IMigrationMetadata.Id
        {
            get { return "201903211006438_Added orders table1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
